[default.extend-words]
homogenous="homogenous"
superioris="superioris"
vas="vas"
musculaire="musculaire"
OME="OME"
terminalis="terminalis"
selectin="selectin"
ANC="ANC"
NNED="NNED"
contagiosum="contagiosum"
Rittler="Rittler"
Pase="Pase"
migrans="migrans"
TRE="TRE"
INH="INH"
HPE="HPE"
MCH="MCH"
Pilar="Pilar"
miliary="miliary"
ONL="ONL"
extraversion="extraversion"
americanus="americanus"
HAE="HAE"
clitoridis="clitoridis"
Ags="Ags"
DAA="DAA"
CLL="CLL"
persistens="persistens"
ABL="ABL"
ASO="ASO"
PN="PN"
DNE="DNE"
GARD="GARD"
pointes="pointes"
Syndrom="Syndrom"
Celcius="Celcius"
