name: 'Create OAK diffs on Pull requests'

on:
    # Triggers the workflow on pull request events for the master branch
    pull_request:
        branches: [ master ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  classify_branch:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.5
    steps:
      - uses: actions/checkout@v4
      - name: Classify ontology
        run: |
            cd src/ontology; make IMP=FALSE PAT=FALSE MIR=FALSE hp-edit.owl && make tmp/hp-edit.obo
            cp tmp/hp-edit.obo tmp/hp-edit-pr.obo
            
      - name: Upload PR hp-edit.obo
        uses: actions/upload-artifact@v4
        with:
          name: hp-edit-pr.obo
          path: src/ontology/tmp/hp-edit-pr.obo
          retention-days: 1
  classify_main:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.5
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: Classify ontology
        run: |
          cd src/ontology; make IMP=FALSE PAT=FALSE MIR=FALSE hp-edit.owl
          robot convert --input hp-edit.owl --output tmp/hp-edit-master.obo --format obo
      # The robot convert above stays for now since the make target is not yet available in the main branch

      - name: Upload master hp-edit.obo
        uses: actions/upload-artifact@v4
        with:
          name: hp-edit-master.obo
          path: src/ontology/tmp/hp-edit-master.obo
          retention-days: 1
  diff_classification:
    needs:
      - classify_branch
      - classify_main
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.5
    steps:
      - uses: actions/checkout@v4
      - name: Download master classification
        uses: actions/download-artifact@v4
        with:
          name: hp-edit-master.obo
          path: src/ontology/tmp/
      - name: Download PR classification
        uses: actions/download-artifact@v4
        with:
          name: hp-edit-pr.obo
          path: src/ontology/tmp/
      - name: Diff classification
        run: | 
            cd src/ontology;
            ls -l tmp/hp-edit-master.obo;
            make gh-action-diff
      - name: Upload diff
        uses: actions/upload-artifact@v4
        with:
          name: difference_main-branch_base.md
          path: src/ontology/reports/difference_main-branch_base.md
  post_comment:
    needs: diff_classification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download reasoned diff
        uses: actions/download-artifact@v4
        with:
          name: difference_main-branch_base.md
          path: src/ontology/reports/
      - name: Prepare reasoned comment
        run: "echo \"<details>\n <summary> Here's a diff of how these changes impact the classified ontology: </summary> \n\" >comment.md; cat src/ontology/reports/difference_main-branch_base.md >>comment.md"
      - name: Post reasoned comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: NejcZdovc/comment-pr@v1.1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          file: "../../comment.md"
          identifier: "REASONED"
      - uses: actions/checkout@v4
      # - name: Download edit diff
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: edit-diff.md
      #     path: edit-diff.md
      # - name: Prepare edit file comment
      #   run: "echo \"<details>\n <summary> Here's a diff of your edit file (unreasoned) </summary> \n\" >edit-comment.md; cat edit-diff.md >>edit-comment.md"
      - name: Post comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: NejcZdovc/comment-pr@v1.1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          file: "../../edit-comment.md"
          identifier: "UNREASONED"