name: Post Markdown Comment on Pull Request

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  post-comment:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.4.3
    env:
      DIFFERENCE_MD_PATH: src/ontology/reports/difference_main-branch_base.md 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install oaklib
        run: pip install oaklib

      - name: Configure git with GitHub Actions user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory /__w/human-phenotype-ontology/human-phenotype-ontology

      - name: Fetch the head branch of the pull request
        run: |
          git fetch origin ${{ github.head_ref }}

      - name: Checkout the head branch of the pull request
        run: |
          git checkout ${{ github.head_ref }}

      - name: Run make kgcl-diff-md-main-branch-base
        run: |
          cd src/ontology
          make kgcl-diff-md-main-branch-base

      - name: Stage the report file
        run: |
          git add ${{ env.DIFFERENCE_MD_PATH }}

      - name: Commit and push if there are changes
        run: |
          git diff --staged --quiet || (git commit -m "Update difference_main-branch_base.md" && git push origin ${{ github.head_ref }})
      
      

      # Post or update comment on pull request if difference_md.md exists
      - name: Post or update comment on pull request
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = process.env.DIFFERENCE_MD_PATH; 
            if (fs.existsSync(path)) {
                let content = fs.readFileSync(path, 'utf8');
                if (content) {
                    // GitHub's max issue body size is approximately 65536 characters
                    const maxBodySize = 65536;
                    const truncateMsg = '\n</details>\n\n ### WARNING: This diff is too large and has been truncated. For full diff see [here](https://github.com/${{ github.repository }}/blob/${{ github.head_ref }}/src/ontology/reports/difference_main-branch_base.md).';
                    if (content.length > maxBodySize) {
                        // Truncate the content to fit within the GitHub comment size limit
                        content = content.substring(0, maxBodySize - truncateMsg.length) + truncateMsg;
                    }

                    const { owner, repo } = context.repo;
                    const { number } = context.issue;
                    const existingComments = await github.rest.issues.listComments({
                        owner,
                        repo,
                        issue_number: number
                    });
                    const existingComment = existingComments.data.find(comment => comment.user.login === 'github-actions[bot]');
                    if (existingComment) {
                        await github.rest.issues.updateComment({
                            owner,
                            repo,
                            comment_id: existingComment.id,
                            body: content
                        });
                    } else {
                        await github.rest.issues.createComment({
                            owner,
                            repo,
                            issue_number: number,
                            body: content
                        });
                    }
                } else {
                    console.log("The markdown file is empty."); // Debug print if the file is empty
                }
            } else {
                console.log("The markdown file does not exist."); // Debug print if the file does not exist
            }
